[package]
name = "gacha-pull"
version = "0.1.0"
edition = "2025"

[dependencies]
rand = "0.8.5"
rayon = "1.7"
once_cell = "1.18"
csv = "1.2"
indicatif = "0.17.11"
lazy_static = "1.5.0"
num_cpus = "1.16.0"
clap = "4.5.31"
